#+ endpoint: https://sparql.hegroup.org/sparql/
#+ defaults:
#+   - term: diacylglycerol 
#+   - limit: 100
#+ transform: {
#+     "Subclasse": "?s",
#+     "Classe": "?ClasseConceito",
#+     "Label": "?ClasseConceitoLabel",
#+     "$anchor": "Label"
#+   }
#+ summary: Retrieve from Multiple Endpoints
#+ description: Retrieve classes relating the searched term and its label from multiple sources

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {  
    ?a ?b ?c.
 
    {
        SERVICE <http://dbpedia.org/sparql> {
            ?d ?p ?o.
        } 
    }  
    UNION
    {
        SERVICE <http://bnb.data.bl.uk/sparql> {  
            ?e ?p2 ?o2.
        }
    } 
}limit 1
