#+ endpoint: https://query.wikidata.org/
#+ defaults:
#+   - term: diacylglycerol 
#+ summary: Retrieve from Multiple Endpoints
#+ description: Retrieve classes relating the searched term and its label from multiple sources
#+ transform: {
#+     "subject": "?subject",
#+     "label": "?label"
#+   }

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?subject ?label WHERE {
    {
        select distinct * where{
             SERVICE silent <https://dbpedia.org/sparql> { 
                ?subject rdfs:label ?label. 
             }
            filter( contains(str(?label),str(?_term_str)))


        }limit 1
    }union{
        select distinct * where{
             SERVICE silent <https://query.wikidata.org/sparql> { 
                ?subject rdfs:label ?label. 
             }
            filter( contains(str(?label),str(?_term_str)))
        }limit 1
    }union{
        select distinct * where{
             SERVICE silent <https://sparql.hegroup.org/sparql/> { 
                ?subject rdfs:label ?label. 
             }
            filter( contains(str(?label),str(?_term_str)))
        }limit 1
    }
 
}limit 1
