#+ endpoint: https://query.wikidata.org/
#+ defaults:
#+   - term: diacylglycerol 
#+ summary: Retrieve from Multiple Endpoints
#+ description: Retrieve classes relating the searched term and its label from multiple sources

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
 
  
  SERVICE <https://dbpedia.org/sparql> {
    { 
      ?subject rdfs:label ?label. 
    }
    UNION { 
      ?subject2 rdfs:label ?label2. 
    }
    filter( contains(str(?label),str(?_term_str)))
    
  }
  
 
}limit 10
