select ?vocab, ?stringPrefix
where{
?vocab <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocommons/voaf#Vocabulary> .
?vocab <http://purl.org/vocab/vann/preferredNamespacePrefix> ?stringPrefix.
}
