#+ tags:
#+   - Busca Termo
#+ endpoint: https://sparql.hegroup.org/sparql/
#+ defaults:
#+   - term: diacylglycerol 
#+   - limit: 100
#+ transform: {
#+     "Subclasse": "?s",
#+     "Classe": "?ClasseConceito",
#+     "Label": "?ClasseConceitoLabel",
#+     "$anchor": "Label"
#+   }
#+ summary: Retrieve from CHEBI
#+ description: Retrieve classes relating the searched term and its label.


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select * {
        GRAPH <http://purl.obolibrary.org/obo/merged/CHEBI> {
            	?s rdfs:subClassOf ?ClasseConceito .
            	?ClasseConceito rdfs:label ?ClasseConceitoLabel .
        }
        
        filter( contains(str(?ClasseConceitoLabel),str(?_term_str)))
}limit 100


