#+ defaults:
#+   - term: a

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct * where {
?vocab <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:Ontology_(information_science)>.
?vocab <http://dbpedia.org/ontology/abstract> ?abstract.
filter( contains(str(?abstract),'ontology'))
filter( contains(str(?abstract),str(?_term_str)))

} LIMIT 1000

