#+ defaults:
#+   - term: diacylglycerol 

PREFIX lodbr: <http://lodbr.ufrj.br/agrotoxicos/propriedade/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select * {
service <https://sparql.hegroup.org/sparql/> {
        GRAPH <http://purl.obolibrary.org/obo/merged/CHEBI> {
            	?s rdfs:subClassOf ?ClasseConceito .
            	?ClasseConceito rdfs:label ?ClasseConceitoLabel .
        }
        filter( contains(str(?ClasseConceitoLabel),str(?_term_str)))
    }
}limit 100


